//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcWorkoutApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class favorite
    {
        public string masterUser { get; set; }
        public string userName { get; set; }
        public string workoutName { get; set; }
    }
}
